image:
  file: .gitpod.Dockerfile

# Commands to start on workspace startup
tasks:
  - init: yarn install
    command: yarn nx serve www
# Ports to expose on workspace startup
ports:
  - port: 4200
    onOpen: open-preview
vscode:
  extensions:
    - naumovs.color-highlight
    - dendron.dendron
    - dendron.dendron-markdown-links
    - dendron.dendron-markdown-shortcuts
    - dendron.dendron-paste-image
    - ms-azuretools.vscode-docker
    - dbaeumer.vscode-eslint
    - manuth.eslint-language-service
    - github.vscode-pull-request-github
    - firsttris.vscode-jest-runner
    - silvenon.mdx
    - nrwl.angular-console
    - csstools.postcss
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - davidanson.vscode-markdownlint
